#include "symbol.h"

namespace xemmai
{

void t_type_of<xraft::t_key>::f_define(t_extension* a_extension)
{
	using namespace xraft;
	t_define<t_key, intptr_t>(a_extension, L"Key")
		(L"NONE", e_key__NONE)
		(L"BACK_SPACE", e_key__BACK_SPACE)
		(L"TAB", e_key__TAB)
		(L"LINEFEED", e_key__LINEFEED)
		(L"CLEAR", e_key__CLEAR)
		(L"RETURN", e_key__RETURN)
		(L"PAUSE", e_key__PAUSE)
		(L"SCROLL_LOCK", e_key__SCROLL_LOCK)
		(L"SYS_REQ", e_key__SYS_REQ)
		(L"ESCAPE", e_key__ESCAPE)
		(L"DELETE", e_key__DELETE)
		(L"HOME", e_key__HOME)
		(L"LEFT", e_key__LEFT)
		(L"UP", e_key__UP)
		(L"RIGHT", e_key__RIGHT)
		(L"DOWN", e_key__DOWN)
		(L"PRIOR", e_key__PRIOR)
		(L"NEXT", e_key__NEXT)
		(L"END", e_key__END)
		(L"BEGIN", e_key__BEGIN)
		(L"SELECT", e_key__SELECT)
		(L"PRINT", e_key__PRINT)
		(L"EXECUTE", e_key__EXECUTE)
		(L"INSERT", e_key__INSERT)
		(L"UNDO", e_key__UNDO)
		(L"REDO", e_key__REDO)
		(L"MENU", e_key__MENU)
		(L"FIND", e_key__FIND)
		(L"CANCEL", e_key__CANCEL)
		(L"HELP", e_key__HELP)
		(L"BREAK", e_key__BREAK)
		(L"MODE_SWITCH", e_key__MODE_SWITCH)
		(L"NUM_LOCK", e_key__NUM_LOCK)
		(L"KP_SPACE", e_key__KP_SPACE)
		(L"KP_TAB", e_key__KP_TAB)
		(L"KP_ENTER", e_key__KP_ENTER)
		(L"KP_F1", e_key__KP_F1)
		(L"KP_F2", e_key__KP_F2)
		(L"KP_F3", e_key__KP_F3)
		(L"KP_F4", e_key__KP_F4)
		(L"KP_HOME", e_key__KP_HOME)
		(L"KP_LEFT", e_key__KP_LEFT)
		(L"KP_UP", e_key__KP_UP)
		(L"KP_RIGHT", e_key__KP_RIGHT)
		(L"KP_DOWN", e_key__KP_DOWN)
		(L"KP_PRIOR", e_key__KP_PRIOR)
		(L"KP_NEXT", e_key__KP_NEXT)
		(L"KP_END", e_key__KP_END)
		(L"KP_BEGIN", e_key__KP_BEGIN)
		(L"KP_INSERT", e_key__KP_INSERT)
		(L"KP_DELETE", e_key__KP_DELETE)
		(L"KP_EQUAL", e_key__KP_EQUAL)
		(L"KP_MULTIPLY", e_key__KP_MULTIPLY)
		(L"KP_ADD", e_key__KP_ADD)
		(L"KP_SEPARATOR", e_key__KP_SEPARATOR)
		(L"KP_SUBTRACT", e_key__KP_SUBTRACT)
		(L"KP_DECIMAL", e_key__KP_DECIMAL)
		(L"KP_DIVIDE", e_key__KP_DIVIDE)
		(L"KP_0", e_key__KP_0)
		(L"KP_1", e_key__KP_1)
		(L"KP_2", e_key__KP_2)
		(L"KP_3", e_key__KP_3)
		(L"KP_4", e_key__KP_4)
		(L"KP_5", e_key__KP_5)
		(L"KP_6", e_key__KP_6)
		(L"KP_7", e_key__KP_7)
		(L"KP_8", e_key__KP_8)
		(L"KP_9", e_key__KP_9)
		(L"F1", e_key__F1)
		(L"F2", e_key__F2)
		(L"F3", e_key__F3)
		(L"F4", e_key__F4)
		(L"F5", e_key__F5)
		(L"F6", e_key__F6)
		(L"F7", e_key__F7)
		(L"F8", e_key__F8)
		(L"F9", e_key__F9)
		(L"F10", e_key__F10)
		(L"F11", e_key__F11)
		(L"F12", e_key__F12)
		(L"SHIFT_L", e_key__SHIFT_L)
		(L"SHIFT_R", e_key__SHIFT_R)
		(L"CONTROL_L", e_key__CONTROL_L)
		(L"CONTROL_R", e_key__CONTROL_R)
		(L"CAPS_LOCK", e_key__CAPS_LOCK)
		(L"SHIFT_LOCK", e_key__SHIFT_LOCK)
		(L"META_L", e_key__META_L)
		(L"META_R", e_key__META_R)
		(L"ALT_L", e_key__ALT_L)
		(L"ALT_R", e_key__ALT_R)
		(L"LEFT_TAB", e_key__LEFT_TAB)
		(L"SPACE", e_key__SPACE)
		(L"EXCLAM", e_key__EXCLAM)
		(L"QUOTEDBL", e_key__QUOTEDBL)
		(L"NUMBERSIGN", e_key__NUMBERSIGN)
		(L"DOLLAR", e_key__DOLLAR)
		(L"PERCENT", e_key__PERCENT)
		(L"AMPERSAND", e_key__AMPERSAND)
		(L"APOSTROPHE", e_key__APOSTROPHE)
		(L"PARENLEFT", e_key__PARENLEFT)
		(L"PARENRIGHT", e_key__PARENRIGHT)
		(L"ASTERISK", e_key__ASTERISK)
		(L"PLUS", e_key__PLUS)
		(L"COMMA", e_key__COMMA)
		(L"MINUS", e_key__MINUS)
		(L"PERIOD", e_key__PERIOD)
		(L"SLASH", e_key__SLASH)
		(L"D0", e_key__0)
		(L"D1", e_key__1)
		(L"D2", e_key__2)
		(L"D3", e_key__3)
		(L"D4", e_key__4)
		(L"D5", e_key__5)
		(L"D6", e_key__6)
		(L"D7", e_key__7)
		(L"D8", e_key__8)
		(L"D9", e_key__9)
		(L"COLON", e_key__COLON)
		(L"SEMICOLON", e_key__SEMICOLON)
		(L"LESS", e_key__LESS)
		(L"EQUAL", e_key__EQUAL)
		(L"GREATER", e_key__GREATER)
		(L"QUESTION", e_key__QUESTION)
		(L"AT", e_key__AT)
		(L"A", e_key__A)
		(L"B", e_key__B)
		(L"C", e_key__C)
		(L"D", e_key__D)
		(L"E", e_key__E)
		(L"F", e_key__F)
		(L"G", e_key__G)
		(L"H", e_key__H)
		(L"I", e_key__I)
		(L"J", e_key__J)
		(L"K", e_key__K)
		(L"L", e_key__L)
		(L"M", e_key__M)
		(L"N", e_key__N)
		(L"O", e_key__O)
		(L"P", e_key__P)
		(L"Q", e_key__Q)
		(L"R", e_key__R)
		(L"S", e_key__S)
		(L"T", e_key__T)
		(L"U", e_key__U)
		(L"V", e_key__V)
		(L"W", e_key__W)
		(L"X", e_key__X)
		(L"Y", e_key__Y)
		(L"Z", e_key__Z)
		(L"BRACKETLEFT", e_key__BRACKETLEFT)
		(L"BACKSLASH", e_key__BACKSLASH)
		(L"BRACKETRIGHT", e_key__BRACKETRIGHT)
		(L"ASCIICIRCUM", e_key__ASCIICIRCUM)
		(L"UNDERSCORE", e_key__UNDERSCORE)
		(L"GRAVE", e_key__GRAVE)
		(L"BRACELEFT", e_key__BRACELEFT)
		(L"BAR", e_key__BAR)
		(L"BRACERIGHT", e_key__BRACERIGHT)
		(L"ASCIITILDE", e_key__ASCIITILDE)
	;
}

void t_type_of<xraft::t_modifier>::f_define(t_extension* a_extension)
{
	using namespace xraft;
	t_define<t_modifier, intptr_t>(a_extension, L"Modifier")
		(L"NONE", e_modifier__NONE)
		(L"SHIFT", e_modifier__SHIFT)
		(L"LOCK", e_modifier__LOCK)
		(L"CONTROL", e_modifier__CONTROL)
		(L"ALTERNATE", e_modifier__ALTERNATE)
		(L"BUTTON1", e_modifier__BUTTON1)
		(L"BUTTON2", e_modifier__BUTTON2)
		(L"BUTTON3", e_modifier__BUTTON3)
		(L"BUTTON4", e_modifier__BUTTON4)
		(L"BUTTON5", e_modifier__BUTTON5)
	;
}

void t_type_of<xraft::t_button>::f_define(t_extension* a_extension)
{
	using namespace xraft;
	t_define<t_button, intptr_t>(a_extension, L"Button")
		(L"NONE", e_button__NONE)
		(L"BUTTON1", e_button__1)
		(L"BUTTON2", e_button__2)
		(L"BUTTON3", e_button__3)
		(L"BUTTON4", e_button__4)
		(L"BUTTON5", e_button__5)
	;
}

}
