#include "symbol.h"

namespace xemmai
{

t_object* t_type_of<xraft::t_key>::f_define(t_library* a_library)
{
	using namespace xraft;
	return t_base::f_define(a_library, [](auto a_fields)
	{
		a_fields
		(L"NONE"sv, e_key__NONE)
		(L"BACK_SPACE"sv, e_key__BACK_SPACE)
		(L"TAB"sv, e_key__TAB)
		(L"LINEFEED"sv, e_key__LINEFEED)
		(L"CLEAR"sv, e_key__CLEAR)
		(L"RETURN"sv, e_key__RETURN)
		(L"PAUSE"sv, e_key__PAUSE)
		(L"SCROLL_LOCK"sv, e_key__SCROLL_LOCK)
		(L"SYS_REQ"sv, e_key__SYS_REQ)
		(L"ESCAPE"sv, e_key__ESCAPE)
		(L"DELETE"sv, e_key__DELETE)
		(L"HOME"sv, e_key__HOME)
		(L"LEFT"sv, e_key__LEFT)
		(L"UP"sv, e_key__UP)
		(L"RIGHT"sv, e_key__RIGHT)
		(L"DOWN"sv, e_key__DOWN)
		(L"PRIOR"sv, e_key__PRIOR)
		(L"NEXT"sv, e_key__NEXT)
		(L"END"sv, e_key__END)
		(L"BEGIN"sv, e_key__BEGIN)
		(L"SELECT"sv, e_key__SELECT)
		(L"PRINT"sv, e_key__PRINT)
		(L"EXECUTE"sv, e_key__EXECUTE)
		(L"INSERT"sv, e_key__INSERT)
		(L"UNDO"sv, e_key__UNDO)
		(L"REDO"sv, e_key__REDO)
		(L"MENU"sv, e_key__MENU)
		(L"FIND"sv, e_key__FIND)
		(L"CANCEL"sv, e_key__CANCEL)
		(L"HELP"sv, e_key__HELP)
		(L"BREAK"sv, e_key__BREAK)
		(L"MODE_SWITCH"sv, e_key__MODE_SWITCH)
		(L"NUM_LOCK"sv, e_key__NUM_LOCK)
		(L"KP_SPACE"sv, e_key__KP_SPACE)
		(L"KP_TAB"sv, e_key__KP_TAB)
		(L"KP_ENTER"sv, e_key__KP_ENTER)
		(L"KP_F1"sv, e_key__KP_F1)
		(L"KP_F2"sv, e_key__KP_F2)
		(L"KP_F3"sv, e_key__KP_F3)
		(L"KP_F4"sv, e_key__KP_F4)
		(L"KP_HOME"sv, e_key__KP_HOME)
		(L"KP_LEFT"sv, e_key__KP_LEFT)
		(L"KP_UP"sv, e_key__KP_UP)
		(L"KP_RIGHT"sv, e_key__KP_RIGHT)
		(L"KP_DOWN"sv, e_key__KP_DOWN)
		(L"KP_PRIOR"sv, e_key__KP_PRIOR)
		(L"KP_NEXT"sv, e_key__KP_NEXT)
		(L"KP_END"sv, e_key__KP_END)
		(L"KP_BEGIN"sv, e_key__KP_BEGIN)
		(L"KP_INSERT"sv, e_key__KP_INSERT)
		(L"KP_DELETE"sv, e_key__KP_DELETE)
		(L"KP_EQUAL"sv, e_key__KP_EQUAL)
		(L"KP_MULTIPLY"sv, e_key__KP_MULTIPLY)
		(L"KP_ADD"sv, e_key__KP_ADD)
		(L"KP_SEPARATOR"sv, e_key__KP_SEPARATOR)
		(L"KP_SUBTRACT"sv, e_key__KP_SUBTRACT)
		(L"KP_DECIMAL"sv, e_key__KP_DECIMAL)
		(L"KP_DIVIDE"sv, e_key__KP_DIVIDE)
		(L"KP_0"sv, e_key__KP_0)
		(L"KP_1"sv, e_key__KP_1)
		(L"KP_2"sv, e_key__KP_2)
		(L"KP_3"sv, e_key__KP_3)
		(L"KP_4"sv, e_key__KP_4)
		(L"KP_5"sv, e_key__KP_5)
		(L"KP_6"sv, e_key__KP_6)
		(L"KP_7"sv, e_key__KP_7)
		(L"KP_8"sv, e_key__KP_8)
		(L"KP_9"sv, e_key__KP_9)
		(L"F1"sv, e_key__F1)
		(L"F2"sv, e_key__F2)
		(L"F3"sv, e_key__F3)
		(L"F4"sv, e_key__F4)
		(L"F5"sv, e_key__F5)
		(L"F6"sv, e_key__F6)
		(L"F7"sv, e_key__F7)
		(L"F8"sv, e_key__F8)
		(L"F9"sv, e_key__F9)
		(L"F10"sv, e_key__F10)
		(L"F11"sv, e_key__F11)
		(L"F12"sv, e_key__F12)
		(L"SHIFT_L"sv, e_key__SHIFT_L)
		(L"SHIFT_R"sv, e_key__SHIFT_R)
		(L"CONTROL_L"sv, e_key__CONTROL_L)
		(L"CONTROL_R"sv, e_key__CONTROL_R)
		(L"CAPS_LOCK"sv, e_key__CAPS_LOCK)
		(L"SHIFT_LOCK"sv, e_key__SHIFT_LOCK)
		(L"META_L"sv, e_key__META_L)
		(L"META_R"sv, e_key__META_R)
		(L"ALT_L"sv, e_key__ALT_L)
		(L"ALT_R"sv, e_key__ALT_R)
		(L"LEFT_TAB"sv, e_key__LEFT_TAB)
		(L"SPACE"sv, e_key__SPACE)
		(L"EXCLAM"sv, e_key__EXCLAM)
		(L"QUOTEDBL"sv, e_key__QUOTEDBL)
		(L"NUMBERSIGN"sv, e_key__NUMBERSIGN)
		(L"DOLLAR"sv, e_key__DOLLAR)
		(L"PERCENT"sv, e_key__PERCENT)
		(L"AMPERSAND"sv, e_key__AMPERSAND)
		(L"APOSTROPHE"sv, e_key__APOSTROPHE)
		(L"PARENLEFT"sv, e_key__PARENLEFT)
		(L"PARENRIGHT"sv, e_key__PARENRIGHT)
		(L"ASTERISK"sv, e_key__ASTERISK)
		(L"PLUS"sv, e_key__PLUS)
		(L"COMMA"sv, e_key__COMMA)
		(L"MINUS"sv, e_key__MINUS)
		(L"PERIOD"sv, e_key__PERIOD)
		(L"SLASH"sv, e_key__SLASH)
		(L"D0"sv, e_key__0)
		(L"D1"sv, e_key__1)
		(L"D2"sv, e_key__2)
		(L"D3"sv, e_key__3)
		(L"D4"sv, e_key__4)
		(L"D5"sv, e_key__5)
		(L"D6"sv, e_key__6)
		(L"D7"sv, e_key__7)
		(L"D8"sv, e_key__8)
		(L"D9"sv, e_key__9)
		(L"COLON"sv, e_key__COLON)
		(L"SEMICOLON"sv, e_key__SEMICOLON)
		(L"LESS"sv, e_key__LESS)
		(L"EQUAL"sv, e_key__EQUAL)
		(L"GREATER"sv, e_key__GREATER)
		(L"QUESTION"sv, e_key__QUESTION)
		(L"AT"sv, e_key__AT)
		(L"A"sv, e_key__A)
		(L"B"sv, e_key__B)
		(L"C"sv, e_key__C)
		(L"D"sv, e_key__D)
		(L"E"sv, e_key__E)
		(L"F"sv, e_key__F)
		(L"G"sv, e_key__G)
		(L"H"sv, e_key__H)
		(L"I"sv, e_key__I)
		(L"J"sv, e_key__J)
		(L"K"sv, e_key__K)
		(L"L"sv, e_key__L)
		(L"M"sv, e_key__M)
		(L"N"sv, e_key__N)
		(L"O"sv, e_key__O)
		(L"P"sv, e_key__P)
		(L"Q"sv, e_key__Q)
		(L"R"sv, e_key__R)
		(L"S"sv, e_key__S)
		(L"T"sv, e_key__T)
		(L"U"sv, e_key__U)
		(L"V"sv, e_key__V)
		(L"W"sv, e_key__W)
		(L"X"sv, e_key__X)
		(L"Y"sv, e_key__Y)
		(L"Z"sv, e_key__Z)
		(L"BRACKETLEFT"sv, e_key__BRACKETLEFT)
		(L"BACKSLASH"sv, e_key__BACKSLASH)
		(L"BRACKETRIGHT"sv, e_key__BRACKETRIGHT)
		(L"ASCIICIRCUM"sv, e_key__ASCIICIRCUM)
		(L"UNDERSCORE"sv, e_key__UNDERSCORE)
		(L"GRAVE"sv, e_key__GRAVE)
		(L"BRACELEFT"sv, e_key__BRACELEFT)
		(L"BAR"sv, e_key__BAR)
		(L"BRACERIGHT"sv, e_key__BRACERIGHT)
		(L"ASCIITILDE"sv, e_key__ASCIITILDE)
		;
	});
}

t_object* t_type_of<xraft::t_modifier>::f_define(t_library* a_library)
{
	using namespace xraft;
	return t_base::f_define(a_library, [](auto a_fields)
	{
		a_fields
		(L"NONE"sv, e_modifier__NONE)
		(L"SHIFT"sv, e_modifier__SHIFT)
		(L"LOCK"sv, e_modifier__LOCK)
		(L"CONTROL"sv, e_modifier__CONTROL)
		(L"ALTERNATE"sv, e_modifier__ALTERNATE)
		(L"BUTTON1"sv, e_modifier__BUTTON1)
		(L"BUTTON2"sv, e_modifier__BUTTON2)
		(L"BUTTON3"sv, e_modifier__BUTTON3)
		(L"BUTTON4"sv, e_modifier__BUTTON4)
		(L"BUTTON5"sv, e_modifier__BUTTON5)
		;
	});
}

t_object* t_type_of<xraft::t_button>::f_define(t_library* a_library)
{
	using namespace xraft;
	return t_base::f_define(a_library, [](auto a_fields)
	{
		a_fields
		(L"NONE"sv, e_button__NONE)
		(L"BUTTON1"sv, e_button__1)
		(L"BUTTON2"sv, e_button__2)
		(L"BUTTON3"sv, e_button__3)
		(L"BUTTON4"sv, e_button__4)
		(L"BUTTON5"sv, e_button__5)
		;
	});
}

}
